export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";

export const FETCH_CHANNEL_DETAIL = "FETCH_CHANNEL_DETAIL";
export const SET_CHANNEL_LOADING = "SET_CHANNEL_LOADING";

export const ADD_CHANNEL = "ADD_CHANNEL";

export const ADD_MESSAGE = "ADD_MESSAGE";
